# NumPy Phase 1  
___

##  What NumPy Actually Is

###  Python List

* Stores references to Python objects.
* Can contain mixed data types.
* Memory is not contiguous.
* Slower for mathematical operations.

###  NumPy `ndarray`

* Stored in a contiguous memory block.
* Fixed data type (`dtype`).
* Fixed size.
* No per-element Python object overhead.
* Uses optimized, vectorized C-level operations.

**Why this matters in ML**

* Faster matrix and numerical computations.
* Better memory efficiency.
* Predictable structure and behavior.

---

##  Axes, Dimensions, and Shape

###  `ndim`

Represents the number of axes (dimensions).

Examples:

* `(3,)` → 1D → 1 axis
* `(3,4)` → 2D → 2 axes
* `(2,3,4)` → 3D → 3 axes

###  `shape`

Defines the size along each axis.

Example:

```python
X = np.array([[1,2,3],
              [4,5,6]])
```

* `ndim = 2`
* `shape = (2,3)`
* Axis 0 → rows → size 2
* Axis 1 → columns → size 3

---

##  1D vs 2D — Critical Difference

| Shape   | Meaning       |
| ------- | ------------- |
| `(3,)`  | Flat vector   |
| `(1,3)` | Row matrix    |
| `(3,1)` | Column matrix |

A 1D array is neither a row nor a column.
This is a common source of silent shape bugs in ML pipelines.

---

In [9]:
# Creation of an Array

import numpy as np 

a = np.array([10, 20, 30, 40])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[10 20 30 40]


In [12]:
# Dimension 
print(a.ndim)

# Shape
print(a.shape)

# Data type of each value
print(a.dtype)

1
(4,)
int64


### NumPy Creation Functions

---

### `np.array()`

**Why used**

* Converts Python lists/tuples into NumPy arrays.
* Gives structured, fast numerical data.

**Syntax**

```python
np.array(data, dtype=None)
```

**Example**

```python
np.array([1,2,3])
np.array([[1,2],[3,4]])
```

---

### `np.zeros()`

**Why used**

* Creates an array filled with zeros.
* Common for initializing weights, buffers, or placeholders.

**Syntax**

```python
np.zeros(shape, dtype=float)
```

**Example**

```python
np.zeros((3,4))
```

---

### `np.ones()`

**Why used**

* Creates an array filled with ones.
* Useful for masks, bias initialization, or testing shapes.

**Syntax**

```python
np.ones(shape, dtype=float)
```

**Example**

```python
np.ones((2,3))
```

---

### `np.arange()`

**Why used**

* Generates evenly spaced values within a range.
* Similar to Python `range()` but returns an ndarray.

**Syntax**

```python
np.arange(start, stop, step)
```

**Example**

```python
np.arange(0,10,2)
```

⚠️ Uses step size — floating steps can introduce precision issues.

---

### `np.linspace()`

**Why used**

* Generates a fixed number of equally spaced points.
* Preferred when you need exact count rather than step size.

**Syntax**

```python
np.linspace(start, stop, num)
```

**Example**

```python
np.linspace(0,1,5)
```

---

### `np.random.rand()`

**Why used**

* Uniform random numbers between 0 and 1.

```python
np.random.rand(3,2)
```

---

### `np.random.randn()`

**Why used**

* Normally distributed random numbers (mean 0, std 1).
* Common in ML weight initialization.

```python
np.random.randn(3,2)
```

---

### `np.random.randint()`

**Why used**

* Random integers in a range.

```python
np.random.randint(low, high, size)
```

Example:

```python
np.random.randint(0,10,(2,3))
```

---

###  Quick Summary

* `array()` → convert existing data
* `zeros()` / `ones()` → structured initialization
* `arange()` → step-based sequences
* `linspace()` → count-based sequences
* `random` → stochastic data generation (ML/testing)


In [25]:
# Examples

arr1 = np.arange(0.0,1.0,0.3)
print(arr1)

arr2 = np.arange(1,10,3)
print(arr2)

arr3 = np.linspace(0,50)
print(arr3)

arr4 = np.random.rand(2,3) # No need of parenthesis


[0.  0.3 0.6 0.9]
[1 4 7]
[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


##  Indexing vs Slicing 

###  Indexing removes an axis

```python
X[0] # This says give me all the values present at row 0
```

If `X.shape = (100,4)`
→ Result shape `(4,)`
Axis 0 is removed.

###  Slicing preserves an axis

```python
X[0:1] # This one also gives the same result but it preserves the dimension in 2D format
```

→ Result shape `(1,4)`
Axis is preserved.

###  Column selection

```python
X[:, 3]     # shape → (100,)
X[:, 3:4]   # shape → (100,1)
```

### Core Rule

* **Indexing → axis removed**
* **Slicing → axis preserved**

---

In [39]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Only first row values
print(X[0])
print(X[0].shape) # 1D Format

print("-------------------------------")

print(X[0:1])
print(X[0:1].shape) # 2D Format here 1 is excluded so only first row is considered

print("-------------------------------")

# All Rows but only first column values
print(X[:,0])
print(X[:,0].shape)

print("-------------------------------")

print(X[:,0:1])
print(X[:,0:1].shape)

[1 2 3]
(3,)
-------------------------------
[[1 2 3]]
(1, 3)
-------------------------------
[1 4 7]
(3,)
-------------------------------
[[1]
 [4]
 [7]]
(3, 1)


##  Boolean Indexing

Example:

```python
mask = X[:,0] > 0
```

* `mask.shape → (100,)`
* Mask aligns with axis 0.
* Must match row count exactly.

Applying the mask:

```python
X[mask]
```

* Filters rows.
* If 30 values are `True` → result shape `(30, n_features)`.
* No broadcasting occurs; shapes must align perfectly.

---

In [42]:
# How boolean indexed values look

X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# get the target values (eg.All the first column values)
target = X[:,0] #(3,)
mask = target > 3

print(target)
print(mask)

# Getting the new X with filtered rows
print(X[mask])


[1 4 7]
[False  True  True]
[[4 5 6]
 [7 8 9]]


In [52]:
# Multiple Masks

mask1 = X[:,0] > 3
mask2 = X[:,1] > 5

print(mask1)
print(mask2)

combined_mask = (mask1 & mask2)
print(combined_mask)

# Combined mask filtering
print(X[combined_mask])



[False  True  True]
[False False  True]
[False False  True]
[[7 8 9]]


### Important rules 

* Always wrap conditions in **parentheses**:

```python
(mask1 & mask2)   # correct
```

because `&` has higher precedence.

* Never do:

```python
mask1 and mask2   # wrong for arrays
```

That’s Python boolean logic, not NumPy element-wise logic.

---

👉 Mental model:

* `&` → element-wise AND
* `|` → element-wise OR
* `~` → element-wise NOT



##  Reshape

###  Core Rule

Total number of elements must remain constant.

Example:

```python
a = np.array([1,2,3,4,5,6])
a.reshape(2,3)
```

Valid because `2 × 3 = 6`.

###  Using `-1`

```python
a.reshape(2, -1)
```

NumPy automatically infers the missing dimension.
Only one `-1` is allowed.

###  What reshape does NOT do

* Does not modify the data.
* Does not reorder memory.
* Does not create new elements.

It only changes how the data is interpreted structurally.

---

##  Transpose

### 2D Case

```python
X.shape = (100,5)
X.T → (5,100)
```

Rows and columns are swapped.

### 1D Case

```python
a.shape = (3,)
a.T → (3,)
```

No change occurs because only one axis exists.

---

##  Adding New Axes

Given:

```python
a = np.array([1,2,3])
```

| Expression       | Result Shape |
| ---------------- | ------------ |
| `a.reshape(1,3)` | `(1,3)`      |
| `a.reshape(3,1)` | `(3,1)`      |
| `a[:, None]`     | `(3,1)`      |
| `a[None, :]`     | `(1,3)`      |

The position of `None` determines where the new axis is inserted.

---

In [57]:
a = np.arange(8)
print(a)

print(a.reshape(2,4))
print("-------------------------")

print(a.reshape(4,2))
print("-------------------------")

print(a.reshape(-1,2))
print("-------------------------")

print(a.reshape(2,-1))
print("-------------------------")

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
-------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
-------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
-------------------------
[[0 1 2 3]
 [4 5 6 7]]
-------------------------


In [61]:
X = np.arange(12).reshape(3,4)

print(X)
print("-------------------------")
print(X.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


##  Structural Convention

Standard shapes:

```
X → (n_samples, n_features)
W → (n_features, n_outputs)
```

Matrix multiplication:

```
X @ W → (n_samples, n_outputs)
```

Avoid relying on `(n,)` vectors in  workflows.
Use explicit 2D structures for clarity and safety.