# Phase 2 — Vectorization & Broadcasting 
___

### Vectorization — The Core Idea

Most think vectorization means “short code”.
Wrong.

**Vectorization = removing Python loops and letting NumPy execute operations in optimized C code.**

### Slow Python loop

```python
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
```

###  Vectorized

```python
result = a + b
```

Why faster?

* No Python iteration overhead
* Continuous memory
* SIMD optimizations underneath

If you still write loops in NumPy… you’re basically throwing away its main advantage.

---

### Element-wise operations you must know

```python
a + b
a - b
a * b
a / b
a ** 2
np.sqrt(a)
np.log(a)
```

Everything above runs element-wise.

---

In [ ]:
# Examples

import numpy as np

a = np.array([1,2,3])
b = np.array([1,4,5])

print(a + b)
print(a * b)
print(a / b)

# Vectorization matrix or vectors to be having same size otherwise it will implement broadcasting

[2 6 8]
[ 1  8 15]
[1.  0.5 0.6]


### Axis Concept 

Axis = **direction of operation**.

Think of a matrix:

```
axis=0 → move DOWN rows (operate column-wise)
axis=1 → move ACROSS columns (operate row-wise)
```

Example:

```python
X = np.array([[1,2,3],
              [4,5,6]])

np.sum(X, axis=0)  # [5,7,9]
np.sum(X, axis=1)  # [6,15]
```
____


### Why Broadcasting Exists 

Imagine you have data:

```
X → shape (100,3)   # 100 samples, 3 features
mean → shape (3,)
```

You want:

```
X - mean
```

Without broadcasting you would need:

```python
for each row:
    subtract mean
```

That would be slow.

So NumPy says:

 “If shapes are compatible, I’ll **pretend** to stretch the smaller array.”

Important:

❗ NumPy does **NOT** actually copy data.
It only *views* the smaller array as bigger.

This is why operations stay fast and memory-efficient.

---

### Broadcasting 

Most imagine NumPy physically expanding arrays.

No.

Think like this:

```
NumPy aligns shapes from RIGHT → LEFT
```

It compares dimensions one by one.

---

### The ONLY Two Rules That Matter

When comparing dimensions:

###  Compatible if:

1. They are equal
   OR
2. One of them is **1**

That’s it. Nothing more.

---

### Step-by-Step Shape Matching

### Example A

```
A → (2,3)
B → (3,)
```

First, NumPy rewrites B as:

```
(1,3)
```

Now compare from right:

```
3 vs 3  
2 vs 1   (1 can stretch)
```

Result shape:

```
(2,3)
```

---

### Example B (VERY IMPORTANT)

```
A → (3,1)
B → (3,)
```

Rewrite B:

```
(1,3)
```

Now compare:

```
1 vs 3  
3 vs 1  
```

Result becomes:

```
(3,3)
```

Why?

Because broadcasting happens **both directions**.

---

### Example C — Invalid Case

```
A → (2,3)
B → (2,)
```

Rewrite:

```
(2,3)
(1,2)
```

Compare:

```
3 vs 2 
```

No dimension is 1 → cannot stretch.

So NumPy refuses.

---

### The Golden Algorithm (How Pros Check Broadcasting)

Whenever you see shapes:

### Step 1 — Right align them

```
(100,3)
    (3,)
```

### Step 2 — Expand missing dimensions with 1

```
(100,3)
(1,3)
```

### Step 3 — Compare each column:

| Dim A | Dim B | OK? |
| ----- | ----- | --- |
| 3     | 3     | ✔   |
| 100   | 1     | ✔   |

Result = max of each column → `(100,3)`

---
