### Dot Product — The Smallest Building Block

Forget formulas for a second.

If you have two vectors:

```
[ w1, w2, w3 ]
[ x1, x2, x3 ]
```

Dot product basically means:

```
multiply → sum
```

NumPy:

```python
np.dot(a, b)
```

Rule:

* For 1D arrays → returns a scalar.
* Shapes must align:

```
(n,) dot (n,)
```

---

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


### Matrix Multiplication 

Dot product was vector · vector.

Now we go:

```
Matrix  ×  Vector
Matrix  ×  Matrix
```

This is what neural networks, linear regression, PCA — everything — runs on.

---

### Core Rule 

For matrix multiplication:

```
(m × n)  @  (n × p)  →  (m × p)
```

Inner dimensions must match.

If they don’t match → NumPy throws an error.

No broadcasting magic here.
Matrix multiplication has strict algebra rules.

---

### Example 1 — Matrix × Vector

```
W → (4,3)
x → (3,)
```

After alignment, NumPy treats `(3,)` like `(3,1)` internally.

Result:

```
(4,)
```

Why?

Because:

```
(4 × 3) @ (3 × 1) → (4 × 1)
```

Then NumPy squeezes to `(4,)`.

---

### Example 2 — Matrix × Matrix

```
A → (2,3)
B → (3,4)
```

Result:

```
(2,4)
```

Always think:

> Rows of first × Columns of second.

---

### NumPy Functions

```python
np.dot(A, B)
np.matmul(A, B)
A @ B
```

For 2D arrays → all behave the same.

But modern practice:

👉 Use `@`
It’s cleaner and clearer.

---

###  Broadcasting vs Matrix Multiply

Very important distinction:

```
*  → element-wise (broadcasting rules apply)
@  → matrix multiplication (linear algebra rules apply)
```
---



In [5]:
a = np.random.randint(0,100,(3,2))
b = np.random.randint(0,100,(2,2))

print(a @ b)
print(np.matmul(a,b))
print(np.dot(a,b))


[[3224 3574]
 [4495 6378]
 [7843 9676]]
[[3224 3574]
 [4495 6378]
 [7843 9676]]
[[3224 3574]
 [4495 6378]
 [7843 9676]]


### Transpose

Transpose flips dimensions.

```
(m × n) → (n × m)
```

NumPy:

```python
A.T
```

In [6]:
print(a.T)

[[31 27 64]
 [11 64 61]]
