
### Boolean Masking 

Mask = array of True/False.

```
mask = X > 5
```

Same shape as X.

When you do:

```
X[mask]
```

NumPy flattens matching elements into 1D result.

⚠ Rule:
Mask must match array shape.

---

In [1]:
import numpy as np

In [2]:
X = np.array([[10, 2, 3],
              [4, 50, 6],
              [7, 8, 90]])

In [4]:
mask = X > 5
print(mask)

[[ True False False]
 [False  True  True]
 [ True  True  True]]


In [5]:
print(X[mask])

[10 50  6  7  8 90]


In [8]:
mask = X[:,0] > 5
print(mask)
print(X[mask])

[ True False  True]
[[10  2  3]
 [ 7  8 90]]


### Conditional Selection

Instead of loops:

```
X[X > 5]
```

This is vectorized filtering.

Used for:

* Removing outliers
* Thresholding
* Data cleaning

---

In [10]:
print(X[X > 5])

[10 50  6  7  8 90]


### `np.where` (Controlled Replacement)

Syntax:

```
np.where(condition, value_if_true, value_if_false)
```

Example:

```
np.where(X > 5, 1, 0)
```

Creates binary classification-style labels.

⚠ If you pass only condition:

```
np.where(X > 5)
```

It returns indices.

---

In [ ]:
X = np.array([[10, 2, 3],
              [4, 50, 6],
              [7, 8, 90]])

np.where(X > 5)

# In the result it represents the row in the first array then column in the second array

(array([0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [14]:
np.where(X > 5, 1, 0)

array([[1, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

### Fancy Indexing

Selecting specific rows/columns using arrays.

Example:

```python
rows = [0,2]
X[rows]
```

Selects row 0 and 2.

Or:

```python
X[:, [0,2]]
```

Select columns 0 and 2.

⚠ Important:
Fancy indexing returns a copy, not a view.

View = Different variable, SAME memory \
Copy = Different variable, DIFFERENT memory


| Operation                  | Copy or View |
| -------------------------- | ------------ |
| Assignment (`Y = X`)       | Same object  |
| Slicing (`:`)              | View         |
| Fancy indexing (`[1,3,5]`) | Copy         |
| Boolean masking            | Copy         |


### `argmax` & `argsort`

These are used constantly in ML.

### `argmax`

Returns index of max value.

```python
np.argmax(X, axis=1)
```

---

### `argsort`

Returns sorted indices.

```python
np.argsort(arr)
```

---

In [ ]:
np.argmax(X, axis=0)
# it performs operation row wise
# returns index of max element in every row

array([0, 1, 2])

In [ ]:
np.argsort(X)
# returns arranged original indices of elements of every row in sorted order

array([[1, 2, 0],
       [0, 2, 1],
       [0, 1, 2]])